### ISSUE TITLE
Intentional ID? 

### ISSUE THREAD

**Issue by aspoehrer** [taylonr/postman#15]
Hi Nate. First of all, really enjoying your Pluralsight course - Postman Fundamentals. Excellent presentation -so easy to follow and learn from. 
I stumbled over the test environment db.test.json because there is only one book but the id is 5. 
I reset it locally after cloning locally and it returns 1 as expected. If I missed a reason it was to start with 5 instead of 1 for one book, please let me know otherwise putting it out there.

**Comment by taylonr** [comment]
Thanks for the kind words.

I started it at an id other than 5 to reflect that test & dev databases can
often have different ids and data in them.

Resetting it isn't bad.

**Comment by aspoehrer** [comment]
Got it!  Thanks for responding. I got the diff in stories but the id got me twisted up. :) 
I love your inclusion of scripture. 
Was a gift. I posted about it on FB. Have a good one.

**Comment by taylonr** [comment]
Thanks you too.
