### ISSUE TITLE
Errors Launching API

### ISSUE THREAD

**Issue by njloki30** [taylonr/postman#17]
I ran the npm install command, however when attempting to run npm run start:dev  i see the following errors and when I check localhost:3000/landing i don't see the API page. I was hoping to get this straightened out so i can continue the course on the pluralsite training of Postman, Thank you !
![image](https://user-images.githubusercontent.com/20994562/84686844-b2a65380-af0a-11ea-9a3c-bc9d5f29b691.png)

**Comment by taylonr** [comment]
Can you include more of the stack trace? Unfortunately, the part you
included doesn't give me much information of what error actually happened.

**Comment by njloki30** [comment]
Thank you for the quick reply, here is the whole window as well as contents from the npm-debug log
![image](https://user-images.githubusercontent.com/20994562/84697804-c65ab580-af1c-11ea-9ec4-4f90cde0493a.png)

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files (x86)\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'start:dev' ]
2 info using npm@2.7.4
3 info using node@v0.12.2
4 verbose node symlink C:\Program Files (x86)\nodejs\\node.exe
5 verbose run-script [ 'prestart:dev', 'start:dev', 'poststart:dev' ]
6 info prestart:dev postman@0.0.0
7 info start:dev postman@0.0.0
8 verbose unsafe-perm in lifecycle true
9 info postman@0.0.0 Failed to exec start:dev script
10 verbose stack Error: postman@0.0.0 start:dev: `nodemon app.js --ignore db.json`
10 verbose stack Exit status 1
10 verbose stack     at EventEmitter.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\lib\utils\lifecycle.js:213:16)
10 verbose stack     at EventEmitter.emit (events.js:110:17)
10 verbose stack     at ChildProcess.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\lib\utils\spawn.js:14:12)
10 verbose stack     at ChildProcess.emit (events.js:110:17)
10 verbose stack     at maybeClose (child_process.js:1015:16)
10 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
11 verbose pkgid postman@0.0.0
12 verbose cwd C:\postman-master
13 error Windows_NT 6.3.9600
14 error argv "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "start:dev"
15 error node v0.12.2
16 error npm  v2.7.4
17 error code ELIFECYCLE
18 error postman@0.0.0 start:dev: `nodemon app.js --ignore db.json`
18 error Exit status 1
19 error Failed at the postman@0.0.0 start:dev script 'nodemon app.js --ignore db.json'.
19 error This is most likely a problem with the postman package,
19 error not with npm itself.
19 error Tell the author that this fails on your system:
19 error     nodemon app.js --ignore db.json
19 error You can get their info via:
19 error     npm owner ls postman
19 error There is likely additional logging output above.
20 verbose exit [ 1, true ]

**Comment by taylonr** [comment]
I can see the error...not yet sure what the problem is. Can you find the node version?

At the command line run: `node -v`

And also find out the version of nodemon

At the command line run: `npm list --depth=0` and scroll until you see `nodemon`

**Comment by njloki30** [comment]
Node version v0.12.2
Nodemon nodemon@1.19.4

![image](https://user-images.githubusercontent.com/20994562/84703791-d5466580-af26-11ea-89ed-90d352745870.png)

**Comment by taylonr** [comment]
Oh...you probably need to update your node version. Long term support is version 12.0 and cutting edge is 14.0. I'm running 13.8.0

**Comment by njloki30** [comment]
Thank you! that seemed to do the trick!
