### ISSUE TITLE
password authentication failed for user "postgres"

### ISSUE THREAD

**Issue by asmythspotx** [taylonr/postman#5]
At the second part of the ReadMe file, when running npm run db:create, this warning appeared in the terminal "password authentication failed for user "postgres""

**Comment by taylonr** [comment]
Does your config file have the password that you configured your database with?

**Comment by asmythspotx** [comment]
No I just brew install Postgres, how do you get access to the config file on a Mac?

**Comment by taylonr** [comment]
Not postgres' config file, the project's config file. It's located under
server/config

Are you following along with the course?

**Comment by asmythspotx** [comment]
I looked back at the video and fixed the problem. Thank you for helping me with the problem

Kind Regards
