### ISSUE TITLE
localhost:3000/books/1 throws internal server error

### ISSUE THREAD

**Issue by Sand-2050** [taylonr/postman#7]
localhost:3000/books/1 throws internal server error. 
Response:
{
    "name": "SequelizeConnectionRefusedError",
    "parent": {
        "errno": "ECONNREFUSED",
        "code": "ECONNREFUSED",
        "syscall": "connect",
        "address": "127.0.0.1",
        "port": 5432
    },
    "original": {
        "errno": "ECONNREFUSED",
        "code": "ECONNREFUSED",
        "syscall": "connect",
        "address": "127.0.0.1",
        "port": 5432
    }
}

Status: 500 Internal Server Error
But this url works: http://localhost:3000/landing
Not sure how to proceed.

**Comment by taylonr** [comment]
Hi,

Could you please post this in the course discussion: https://app.pluralsight.com/library/courses/postman-fundamentals/discussion

It makes it easier for people to search for their error, in case someone else has already had it. And that way I can not only help you, but anyone in the future who might run in to the same thing.
