### ISSUE TITLE
Problem installing

### ISSUE THREAD

**Issue by BuxomSpaceFish** [taylonr/postman#9]
I'm trying to get set up for your class on Pluralsight and I'm getting this error. I've installed node.js, Postman and git. I've tried googling with zero luck. Any thoughts?

Thank you!

At first I got this error 
'sequelize' is not recognized as an internal or external command,
operable program or batch file.

and fixed it by running 
C:\Users\buxom\Documents\GitHub\postman>npm install --save sequelize

ERROR FOLLOWS
C:\Users\buxom\Documents\GitHub\postman>npm run db:create

> postman@0.0.0 db:create C:\Users\buxom\Documents\GitHub\postman
> sequelize db:create && npm run db:migrate && npm run db:seed

Sequelize CLI [Node: 12.13.1, CLI: 3.2.0, ORM: 4.44.3]

WARNING: This version of Sequelize CLI is not fully compatible with Sequelize v4. https://github.com/sequelize/cli#sequelize-support

Loaded configuration file "server\config\config.json".
Using environment "development".
sequelize deprecated String based operators are now deprecated. Please use Symbol based operators for better security, read more at http://docs.sequelizejs.com/manual/tutorial/querying.html#operators node_modules\sequelize\lib\sequelize.js:245:13

ERROR: connect ECONNREFUSED 127.0.0.1:5432

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! postman@0.0.0 db:create: `sequelize db:create && npm run db:migrate && npm run db:seed`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the postman@0.0.0 db:create script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\buxom\AppData\Roaming\npm-cache\_logs\2019-11-21T15_07_18_448Z-debug.log

**Comment by BuxomSpaceFish** [comment]
Apparently it is looking for Postgres (I saw no mention of needing that in the tutorial) so I installed it and now it tells me "password authentication failed for user "postgres"" - what file do I need to put in my password so I can start work on this class?

Thank you!

**Comment by taylonr** [comment]
In module 2, clip 3 "Getting Started: API" it walks through installing
postgres. That clip also walks through setting up the password.

**Comment by BuxomSpaceFish** [comment]
Apparently after installing node.js and github my browser didn't save my place in the class and I missed that part. 

Thank you very much for the quick response!
